### ISSUE TITLE
BOMs in XML files confuse the parser

### ISSUE THREAD

**Issue by swsch** [ZUGFeRD/mustangproject#99] opened 2019-07-08 14:27 UTC
I just synced my local repo and once again I get an error during testing:

```Running org.mustangproject.ZUGFeRD.MustangReaderWriterCustomXMLTest
[Fatal Error] :1:1: Content ist nicht zul�ssig in Prolog.
Jul 08, 2019 3:15:46 PM org.mustangproject.ZUGFeRD.ZUGFeRDImporter extractString
SCHWERWIEGEND: null
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content ist nicht zul�ssig in Prolog.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at org.mustangproject.ZUGFeRD.ZUGFeRDImporter.getDocument(ZUGFeRDImporter.java:183)
	at org.mustangproject.ZUGFeRD.ZUGFeRDImporter.extractString(ZUGFeRDImporter.java:194)
	at org.mustangproject.ZUGFeRD.ZUGFeRDImporter.getAmount(ZUGFeRDImporter.java:269)
	at org.mustangproject.ZUGFeRD.MustangReaderWriterCustomXMLTest.testCustomZF2Export(MustangReaderWriterCustomXMLTest.java:277)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
```

If BOMs appear in the wild, then I guess a good (maybe even the correct?) place would be right before line 183 in ZUGFeRDImporter.java, method getDocument:

```
182:		DocumentBuilder builder = xmlFact.newDocumentBuilder();
183:		Document doc = builder.parse(new ByteArrayInputStream(rawXML));
```

I think I saw a nifty BOM check somewhere on StackExchange, which I could apply here. The idea is to skip the first bytes if the first *char* read from the input stream is the Unicode BOM. Ah ... [found it again](https://stackoverflow.com/a/18275066).

An alternative would be to use the [Apache Commons](http://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/input/BOMInputStream.html), but that would introduce another dependency to the project.

Opinions anybody?

**Comment by jstaerk** [comment] 2019-07-09 13:43
On my Mac `mvn clean package` runs the tests successfully and I had assumed my BOM detection and removal worked.
Since apparently the windows build does not work on the moment I assume you build on linux? Are there any other steps to reproduce the issue?

**Comment by swsch** [comment] 2019-07-09 14:14
ah ... that would explain why running the unit test directly from IntelliJ works but the maven test job fails, as I am indeed currently working on Windows.

Any idea about what might be the problem on windows?

**Comment by swsch** [comment] 2019-07-09 18:05
@jstaerk 

What happens on your Mac, if you change line 67 in MustangReaderWriterCustomXMLTest.java
from 

    String ownZUGFeRDXML = new String(UTF8ByteOrderMark) + "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +

to
    String ownZUGFeRDXML = "\uFEFF<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +

and then `mvn test`?

Because _this single change_ is enough to get the following result on my Windows box:

    Tests run: 16, Failures: 0, Errors: 0, Skipped: 0
    
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------

If this works on your end, too, then it looks like I have been suffering from "double encoding of the BOM", as the `new String(UTF8ByteOrderMark)` encoded the already encoded BOM character `\uFEFF` again. 

I ran a simple test in something IntelliJ calls "JShell" (never used before):
```
void dump(String s) {
    try {
        byte[] bs = s.getBytes("UTF-8");
        for (byte b : bs) {
            System.out.print(String.format("%x ", b));
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    System.out.println();
}

dump("\uFEFF<xml?");
dump(new String(new byte[]{(byte) 0xef, (byte) 0xbb, (byte) 0xbf}) + "<xml?");
```
and the results match what I saw earlier during a "printf-debugging" orgy:
```
method void dump(String)
dump("\uFEFF<xml?");
dump(new String(new byte[]{(byte) 0xef, (byte) 0xbb, (byte) 0xbf}) + "<xml?");
ef bb bf 3c 78 6d 6c 3f 
c3 af c2 bb c2 bf 3c 78 6d 6c 3f 
```

**Comment by jstaerk** [comment] 2019-07-13 14:10
I merged your pull request - thanks a lot - and with \uFEFF it would still work. And thanks for two-byte BOM support, i actually thought that little sucker was always three bytes.
My issue is: Would \uFEFF not result in a UTF16BE BOM? I consider the rest UTF-8 so I would like to go for a EFBBBF BOM. But somehow \uEFBBBF does not work?
I have no idea what the issue is with windows but the source files are all checked out as UTF8? Your IDE is also set to UTF8?  Does the windows build work like this?

**Comment by swsch** [comment] 2019-07-13 16:12
We have to distinguish between characters in the string, which are 16-bit values according to java, and the _encoded_ bytes derived from that string. Quoting [Wikipedia](https://de.wikipedia.org/wiki/Byte_Order_Mark):

> Als Byte Order Mark (BOM; deutsch Byte-Reihenfolge-Markierung) wird eine charakteristische Bytefolge, die das Unicode-Zeichen U+FEFF (englisch zero width no-break space) codiert, am Anfang eines Datenstroms bezeichnet. Diese Bytefolge dient als Kennung zur Definition der Byte-Reihenfolge und Kodierungsform in UCS/Unicode-Zeichenketten, insbesondere Textdateien.

The BOM in a byte-oriented representation is then the result of encoding this unicode codepoint according to the rules given by the chosen encoding. So UTF-8 makes it EF BB BF, UTF-16 (BE) gives FE FF, UTF-16 (LE) gives FF FE etc. Mathematically speaking, we have a mapping between encodings and their result for the input \uFEFF. This mapping is bijective so that by investigating the result, you can deduce the encoding.

Re: "issue with windows". It's not "Windows" per se, as the unit test succeeded with IntelliJ's test runner, but failed when executed via maven. According to my inner Sherlock Holmes this means that IntelliJ is setting up a UTF-8 based environment, while maven uses the "default" environment provided by the operating system. On a linux box, this would be whatever LANG settings are in use, as the Mac is Unix-based, too, I'd expect the same thing there. Windows, at least as far as I am aware of, does not support changing the locale to UTF-8-friendly settings like 'de_DE.utf-8' or 'en_US.utf-8' but is firmly stuck with its internal encoding, which are either 8-bit ISO-8859-15 or some two-byte thingie for which I can't remember the name right now.

All together, I guess we're seeing the effects of the String constructor described [here](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#String-byte:A-):
> Constructs a new String by decoding the specified array of bytes using the platform's default charset.

So on your Mac, decoding EF BB BF gives \uEFFF, but Windows default settings decode to something different.

**Comment by swsch** [comment] 2019-07-13 19:26
I cobbled together a tiny maven project with the following code:
```
public class Main {
    public static void main(String[] args) {
        printEncodings();
    }

    public static void printEncodings() {
        Properties ps = System.getProperties();
        Enumeration keys = ps.keys();
        while (keys.hasMoreElements()) {
            String key = (String) keys.nextElement();
            if (key.contains("encoding")) {
                System.out.println(String.format("%s: %s", key, ps.getProperty(key)));
            }
        }
        dumpBOM("Cp1252");
        dumpBOM("UTF-8");
    }

    static void dumpBOM(String encoding) {
        try {
            System.out.print(encoding + ": ");
            String s = new String(new byte[]{(byte) 0xef, (byte) 0xbb, (byte) 0xbf}, encoding);
            byte[] bs = s.getBytes("UTF-8");
            for (byte b : bs) {
                System.out.print(String.format("%x ", b));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println();
    }
}
```
and a similarly dumb test case
```
public class MainTest {

    @Test
    public void main() {
        Main.printEncodings();
    }
}
```
Running Main and MainTest from within IntelliJ prints (sorted for easier comparison):
```
file.encoding.pkg: sun.io
file.encoding: UTF-8
ibm.system.encoding: Cp1252
os.encoding: UTF8
sun.io.unicode.encoding: UnicodeLittle
sun.jnu.encoding: Cp1252

Cp1252: c3 af c2 bb c2 bf 
UTF-8: ef bb bf 
```

Running the maven test from within IntelliJ and from cmd.exe results in:
```
file.encoding.pkg: sun.io
file.encoding: Cp1252
ibm.system.encoding: Cp1252
os.encoding: UTF8
sun.io.unicode.encoding: UnicodeLittle
sun.jnu.encoding: Cp1252

Cp1252: c3 af c2 bb c2 bf 
UTF-8: ef bb bf 
```
So we _have_ a difference between the environments and this difference can be mitigated by making the encoding explicit. 

The good news is that the universe is still following the usual rules.

**Closed** 2019-07-23 16:45 UTC
