### ISSUE TITLE
Disable logfile / different logfile-path

### ISSUE THREAD

**Issue by omocinteractive** [ZUGFeRD/mustangproject#235] opened 2021-03-29 09:22 UTC
It is possible to prevent writing a logfile (/log) or to set a different path to the actually path?

Problem: mustang is called from different subdirectories and is writing in each directory /log.

Kind regards!

**Comment by jstaerk** [comment] 2021-04-04 10:38
hi, duplicate of #215 , so far I failed to implement at least the possibility to disable file log output, help is very much appreciated.

**Closed by jstaerk** 2021-04-04 10:38 UTC
