### ISSUE TITLE
Creating PDF for visualisation fails with mustang-cli 2.14.0

### ISSUE THREAD

**Issue by Heavenfighter** [ZUGFeRD/mustangproject#495] opened 2024-09-27 10:44 UTC
The creation of a PDF from XRechnung in UBL Format fails with mustang-cli in version 2.14.0.

Call was:
`java -jar Mustang-CLI-2.13.0.jar --action pdf --source XRechnung_UBL.xml --out test.pdf`

Output:
```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
ZUGFeRD XML source set to XRechnung_UBL.xml
Target set to test.pdf
Error on line 2 column 3
  SXXP0003   Error reported by XML parser: Content ist nicht zulõssig in Prolog.
Error
  SXXP0003  SXXP0003   Error reported by XML parser: Content ist nicht zulõssig in Prolog.
null
Written to test.pdf
```

[XRechnung_UBL.zip](https://github.com/user-attachments/files/17162957/XRechnung_UBL.zip)

**Comment by jstaerk** [comment] 2024-09-28 10:19
closing as dupe of #481, I was just working on it ;-)

**Closed by jstaerk** 2024-09-28 10:19 UTC
