### ISSUE TITLE
crash after invoking ZUGFeRD2PullProvider 

### ISSUE THREAD

**Issue by banifou** [ZUGFeRD/mustangproject#505] opened 2024-10-05 12:35 UTC
I'm pretty new to ZUGFeRD. I implemented the code advised here (https://www.mustangproject.org/use/#xrechnung) to generate a XML XRechnung.

When I run my code, it crashes at this line: ```
ZUGFeRD2PullProvider zf2p = new ZUGFeRD2PullProvider();```
and the error is: 
`Caused by: java.lang.NoClassDefFoundError: org/dom4j/DocumentException`

What am I doing wrong? Thanks

**Comment by J-N-K** [comment] 2024-10-05 12:36
Maven? Gradle?

**Comment by banifou** [comment] 2024-10-05 17:52
Maven.
```
        <dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
            <version>2.3.33</version>
        </dependency>
```
and Java 17.

**Comment by J-N-K** [comment] 2024-10-05 18:07
We use

```
        <!-- mustang -->
        <dependency>
            <groupId>org.mustangproject</groupId>
            <artifactId>library</artifactId>
            <version>2.13.0</version>
        </dependency>
        <dependency>
            <groupId>org.dom4j</groupId>
            <artifactId>dom4j</artifactId>
            <version>2.1.4</version>
        </dependency>
        <dependency>
            <groupId>net.sf.saxon</groupId>
            <artifactId>Saxon-HE</artifactId>
            <version>12.4</version>
        </dependency>
```

Unfortunately the POM on maven central is missing some dependencies.

**Comment by banifou** [comment] 2024-10-05 18:21
Ah, it's working now! Thanks.
Please update the "Usage" part in the Readme.

**Comment by J-N-K** [comment] 2024-10-05 18:26
No, IMO the POM should be fixed. I'm working on that.

**Comment by jstaerk** [comment] 2024-10-06 07:36
thanks for the fix, closing as dupe of https://github.com/ZUGFeRD/mustangproject/issues/422 see there for workaround (the classifier is missing)

**Closed** 2024-10-14 11:11 UTC
