### ISSUE TITLE
ZUV isn't able to extract XML from pdf-file

### ISSUE THREAD

**Issue by simplythomasjay** [ZUGFeRD/mustangproject#211] opened 2020-12-18 17:20 UTC
I'm creating a PDF/A-3b-file with Amyuni-pdf-lib.

I change the XMP-Metadata according to the requirements.

I inject the xml-file into the pdf-file.

ZUV is validating the XMP-Metadata.
PDF/A-3b is correct.
Everything is fine.

But when it comes to extracting the XML-file it is not possible to extract the XML-file and I cannot find the root cause.

The Zugferd-1-Validator from gefeg didn't have any issues with the pdf-file (with the file injection).
 
[Rechn.pdf](https://github.com/ZUGFeRD/ZUV/files/5717124/Rechn.pdf)

I am currently discussing this topic with amyuni but we have no clue.

Best regards.
Thomas

**Comment by jstaerk** [comment] 2020-12-19 08:06
I can reproduce the issue and you are right, at at first validation eveything seems to be OK, my current theory is that the UF key is misleading but I need to have a deeper look. Since ZUV has been completely integrated into Mustang I transferred the issue.

**Comment by heisej** [comment] 2020-12-19 11:02
When I open the pdf file with a pdf viewer under Linux the filename of the embedded XML is shown as "c//FLOBAY8//temp/factur-x.xml" not just "factur-x.xml". This probably is the cause that ZUV can't extract the file.

The rdf part of the pdf file seems to be okay but the embedded file object itself seems to contain the complete path and not just the base name.

**Comment by simplythomasjay** [comment] 2020-12-21 08:22
Thank you.
This is something that the guys from Amyuni and I can work with.

Tomorrow I am able to give a feedback on this.

**Comment by jstaerk** [comment] 2020-12-21 09:25
I just run a trace and this will actually fix the issue. You can also see with [itext rups](https://github.com/itext/rups/releases) that it's the wrong name

**Closed by jstaerk** 2020-12-21 09:25 UTC
