### ISSUE TITLE
ClassNotFoundException after Update from 2.11 to 2.14

### ISSUE THREAD

**Issue by Malte-Neu** [ZUGFeRD/mustangproject#502] opened 2024-10-04 14:22 UTC
I use Maven for my project and have updated the version of the dependency in the pom.xml. After updating from 2.11 to 2.14 of the library project, I get a java.lang.ClassNotFoundException: org.apache.xmpbox.xml.XmpParsingException.

An output from (excerpt)
```
mvn dependency:tree
[INFO] en.prisma.one:ElectronicInvoice:jar:6.7.0-SNAPSHOT
[INFO] +- org.mustangproject:library:jar:2.14.0:compile
[INFO] +- org.mustangproject:validator:jar:2.14.0:compile
[INFO] | +- org.dom4j:dom4j:jar:2.1.4:compile
```

I'm just a simple Maven user and don't know much about it, but it looks to me like something is wrong here, because there are no other dependencies listed in the library project.

Another interesting thing is the manual query from maven central. https://repo.maven.apache.org/maven2/org/mustangproject/library/2.14.0/library-2.14.0.pom
there is no pdf-box in the dependencies.

If I retrieve the old version https://repo.maven.apache.org/maven2/org/mustangproject/library/2.11.0/library-2.11.0.pom, pdfbox is listed in the dependencies.

Is it possible that a wrong file was stored in maven-central?

Best regards,
Malte

**Comment by jstaerk** [comment] 2024-10-05 08:05
dupe of #422 see there for workaround

**Closed by jstaerk** 2024-10-05 08:05 UTC
