### ISSUE TITLE
PDF/A3 conversion not valid

### ISSUE THREAD

**Issue by schmidt-uni-leipzig** [ZUGFeRD/mustangproject#63] opened 2018-09-24 14:06 UTC
I tried to convert a PDF/A-1a file to PDF/A-3a using mustang. According to http://www.mustangproject.org/use.html#pdfa3, this conversion can be done using the command line.

As a result, I created a new PDF file. This PDF is not valid according to verapdf, because "The value of pdfaid:part shall be the part number of ISO 19005 to which the file conforms.".

The result of exiftool shows, that the part is sill set to 1 instead of 3.

So, is it possible to set the correct part number within the conversion process?

**Comment by jstaerk** [comment] 2018-09-24 18:09
i can reproduce the issue

**Comment by jstaerk** [comment] 2018-09-28 06:27
The steps to reproduce were: download mustangproject.org/files/MustangGnuaccountingBeispielRE-20170509_505blanko.pdf as invoice.pdf, run ´java -jar mustang-1.5.4.jar -a´, the resulting invoice.a3.pdf remains PDF/A-1.

That was caused because the non-ZUGFeRD load process did not invoke my "prepareDocument" at all, which would have changed the metadata. 

That's now fixed, please confirm with the interim version on http://www.mustangproject.org/deploy/mustang-1.5.5-SNAPSHOT.jar

VeraPDF has apparently improved and now also shows errors which went undetected before. To follow up on *these* errors is a different issue, I created #64 for this.

**Closed** 2018-09-28 06:27 UTC

**Comment by schmidt-uni-leipzig** [comment] 2018-10-08 14:11
Thank you for you commit.

I checked out the latest mustang version and retried to convert a PDF/A-1A file (see procedure above).

Today, I get a PDF/A-3U instead of a PDF/A-3A file! Furthermore, the XMP Schemas is empty.

To reproduce this information, you can use exiftool: https://www.sno.phy.queensu.ca/~phil/exiftool/

here are my results


```
exiftool -xmp:all pdf1afile.pdf

Part                            : 1
Conformance              : A
```

```
exiftool -xmp:all convertedpdf3afile.pdf

Part                            : 3
Conformance              : U
Schemas                     : 
```

So, the Schemas XMP Property is new and has not a correct value (see #64) and the conformance level is not right.

Could you reopen this issue again?
