### ISSUE TITLE
Remove logback.xml from Library

### ISSUE THREAD

**Issue by christianbuerckert** [ZUGFeRD/mustangproject#215] opened 2021-01-11 09:52 UTC
Adding a logback.xml in a library is very strange. It might also cause strange behaviours in the final applications. Please remove the logback.xml from the repository.

As far as I know a java library should never contain a logback.xml. It's part of the runnable application to define how the logging works and not of the dependencies you use in there. 

If you need a logback definition for unit tests you may place it in the test-resources folder.

**Comment by jstaerk** [comment] 2021-01-11 09:58
Please feel free to PR, the requirement is that validations should be logged in monthly logfile like it was in ZUV

**Comment by mpretzer** [comment] 2021-01-13 09:48
Which application has this requirement of monthly logging? The logback.xml of *that* application should be responsible for setting this up.

Suggestion: remove logback.xml from `/library/src/main/resources/` but keep it in `/Mustang-CLI/src/main/resources`

**Comment by prosdl** [comment] 2021-01-13 11:39
I think it should also be removed from `/validator/src/main/resources/`.

**Comment by w1rth** [comment] 2021-03-28 13:17
As workaround you can use the explicit configuration (in spring boot) something like LOGGING_CONFIG=classpath:logback-spring.xml and in non spring boot apps like mentioned here http://logback.qos.ch/manual/configuration.html#configFileProperty

**Comment by jstaerk** [comment] 2021-04-04 10:35
very helpful, thank you! actually for Mustang 2 I had failed to add a command line parameter to disable logging.

**Comment by omocinteractive** [comment] 2021-05-05 20:54
@jstaerk Did you add this parameter in 2.1.1?  it is "[--no-notices]: refrain from reporting notices"?

**Comment by erwinw** [comment] 2021-07-28 17:51
Isn’t it up to the implementing application to decide what to do with the log file, and the library to provide the log statements? As it is the logback.xml is interfering with our logging configuration :-(

Maybe including the logback configuration in the documentation would help those that do want to have this configured in this way?

**Comment by martinariehm** [comment] 2021-10-12 16:05
Yes, please remove the logback.xml as it messes up our configuration as well.

**Comment by jstaerk** [comment] 2021-12-06 12:08
@omocinteractive I don't remember when I added that, I would probably look in the history.md why is that important?
At the same time I tried to add an option to disable logging into files at all but I did not succeeed.

**Comment by jstaerk** [comment] 2021-12-06 12:09
Please send me a pull request on that issue because I have no idea how to retain the functionality (logging all validations and their results into a monthly file) without that file.

**Comment by omocinteractive** [comment] 2021-12-06 16:22
@jstaerk everything okay, I have resigned myself to the fact that is logged :)

**Comment by martinariehm** [comment] 2021-12-06 16:59
logback.xml must be in the code using the library, not in the library itself. So probably moving the logback.xml from the library to whatever program you were implementing that wanted that kind of logging should solve the issue.

**Comment by jstaerk** [comment] 2022-01-02 04:58
I tried (again) but I do not get this to work, see #259 and it's branch

**Comment by felixxxxxs** [comment] 2022-02-21 23:36
> how to retain the functionality (logging all validations and their results into a monthly file)

Imho this should definitely not be part of the library. Applications that wish to do this can implement that themselves easily by configuring their own logging, while all other users can tune the log output to their own requirements.

As written before, the library's logback.xml config file interferes with the application's own log configuration. Should I remove it and open a PR? 🙂

**Comment by jstaerk** [comment] 2022-04-26 17:25
I'm not sure about the core library but at least in the validator-cli and thus much likely in the validator library this is used to log e.g. which errors the files contain which should be retained. If you have a better alternative yes, please, of course open a PR, maybe before changing everything we start with a small incomplete PR to see if that goes in the correct direction

**Comment by martinariehm** [comment] 2022-05-02 08:25
Moving the logback.xml from library to validator-cli is exactly what is needed imho. Logback configuration is done in the main programs that are using logback not in the libraries they are using.

**Comment by kumboleijo** [comment] 2022-08-04 07:22
Stumbled into the same Issue - setting `logging.config=classpath:logback-spring.xml` inside the `application.properties` + providing a custom logback XML file solved it for me (thanks @w1rth).

Because I stumbled a bit first with that approach here are the reproducable steps I took:

**Before**
```log
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.7.2)

09:15:25.923 [main] INFO  com.example.Application - Starting Application using Java 17.0.3 on VM with PID 71000 
09:15:25.925 [main] INFO  com.example.Application - No active profile set, falling back to 1 default profile: "default"
09:15:26.433 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8080"]
09:15:26.433 [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
09:15:26.434 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.65]
09:15:26.472 [main] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
09:15:26.984 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8080"]
09:15:26.999 [main] INFO  com.example.Application - Started Application in 1.222 seconds (JVM running for 1.424)
```

**After**
```log
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.7.2)

2022-08-04 09:17:36.798  INFO 71206 --- [           main] com.example.Application                   : Starting Application using Java 17.0.3 on VM with PID 71206
2022-08-04 09:17:36.799  INFO 71206 --- [           main] com.example.Application                   : No active profile set, falling back to 1 default profile: "default"
2022-08-04 09:17:37.300  INFO 71206 --- [           main] o.apache.catalina.core.StandardService    : Starting service [Tomcat]
2022-08-04 09:17:37.300  INFO 71206 --- [           main] org.apache.catalina.core.StandardEngine   : Starting Servlet engine: [Apache Tomcat/9.0.65]
2022-08-04 09:17:37.339  INFO 71206 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]        : Initializing Spring embedded WebApplicationContext
2022-08-04 09:17:37.833  INFO 71206 --- [           main] com.example.Application                   : Started Application in 1.171 seconds (JVM running for 1.366)
```

## How-to

**Overview**
```
.
├── main
│   ├── kotlin
│   │   └── de
│   └── resources
│       ├── static
│       ├── templates
│       ├── application.properties  <-- set `logging.config` property
│       └── logback-spring.xml      <-- create custom logback file
└── test
    └── kotlin
        └── de
```

**`application.properties`**
```config
#...

# logging
logging.config=classpath:logback-spring.xml

#...
```

**`logback-spring.xml`**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <include resource="com/google/cloud/spring/logging/logback-appender.xml"/>
    <include resource="com/google/cloud/spring/logging/logback-json-appender.xml"/>
    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
    <include resource="org/springframework/boot/logging/logback/console-appender.xml"/>

    <springProfile name="!dev">
        <!-- This is for the local environment -->
        <root level="INFO">
            <appender-ref ref="CONSOLE"/>
        </root>
    </springProfile>

    <springProfile name="dev">
        <root level="INFO">
            <appender-ref ref="CONSOLE_JSON"/>
        </root>
    </springProfile>
</configuration>
```

Within that logging file you can now customize the logging behaviour of your application.

**Comment by Sarenor** [comment] 2024-02-02 14:23
If you come by this issue now, the problem definitely doesn't exist in Mustang ``2.10.0`` anymore, all you need to do is update your Mustang version.

I did have to explicitly include
```groovy
    implementation group: 'xerces', name: 'xercesImpl', version: '2.12.2'
```
as a dependency since Mustangs transitive dependencies pulled in another parser that didn't support the features my local logback wanted, but that's not a Mustang problem.

Thanks for the library and you might want to close this issue, seeing as the logback.xml is indeed gone :)

**Comment by w1rth** [comment] 2024-10-17 21:00
Happily 🎁 I can confirm that the logback.xml file is gone in the latest version. This issue should be closed.

**Closed** 2024-11-21 11:33 UTC
