### ISSUE TITLE
NoClassDefFoundError: org/apache/pdfbox

### ISSUE THREAD

**Issue by banifou** [ZUGFeRD/mustangproject#512] opened 2024-10-09 15:28 UTC
When I try to merge my PDF invoice with the xml XRechnung using the code described here: https://www.mustangproject.org/use/#custom, following exception is thrown:
`Caused by: java.lang.NoClassDefFoundError: org/apache/pdfbox/pdmodel/common/COSObjectable`

Which pdfbox package and version should I use? 
Right now I use in Maven project:

```
        <dependency>
            <groupId>org.mustangproject</groupId>
            <artifactId>library</artifactId>
         <version>2.14.0</version>
        </dependency>
        <dependency>
            <groupId>org.dom4j</groupId>
            <artifactId>dom4j</artifactId>
            <version>2.1.4</version>
        </dependency>
        <dependency>
            <groupId>net.sf.saxon</groupId>
            <artifactId>Saxon-HE</artifactId>
            <version>12.4</version>
        </dependency>
        
        <dependency>
            <groupId>org.mustangproject</groupId>
            <artifactId>validator</artifactId>
            <classifier>shaded</classifier>
            <version>2.14.1</version>
        </dependency>
```
Thanks

**Comment by banifou** [comment] 2024-10-09 19:01
This is this line of code which is causing the error:
`ZUGFeRDExporterFromA1 ze = new ZUGFeRDExporterFromA1().load(myPDF.pdf);`

**Comment by J-N-K** [comment] 2024-10-09 19:43
```
        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>pdfbox</artifactId>
            <version>${pdfbox.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>preflight</artifactId>
            <version>${pdfbox.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>xmpbox</artifactId>
            <version>${pdfbox.version}</version>
        </dependency>
```

And pdfbox version 3.0.3.

**Comment by jstaerk** [comment] 2024-10-23 08:27
dupe of #505 , closed

**Closed by jstaerk** 2024-10-23 08:27 UTC
